export interface CountryCode {
  country: string;
  code: string;   // dial code, e.g. "+251"
  iso: string;    // ISO 3166-1 alpha-2
  flag: string;   // emoji flag
}

export const COUNTRY_PHONE_CODES: CountryCode[] = [
  { country: "Afghanistan", code: "+93", iso: "AF", flag: "🇦🇫" },
  { country: "Albania", code: "+355", iso: "AL", flag: "🇦🇱" },
  { country: "Algeria", code: "+213", iso: "DZ", flag: "🇩🇿" },
  { country: "Andorra", code: "+376", iso: "AD", flag: "🇦🇩" },
  { country: "Angola", code: "+244", iso: "AO", flag: "🇦🇴" },
  { country: "Argentina", code: "+54", iso: "AR", flag: "🇦🇷" },
  { country: "Armenia", code: "+374", iso: "AM", flag: "🇦🇲" },
  { country: "Australia", code: "+61", iso: "AU", flag: "🇦🇺" },
  { country: "Austria", code: "+43", iso: "AT", flag: "🇦🇹" },
  { country: "Azerbaijan", code: "+994", iso: "AZ", flag: "🇦🇿" },
  { country: "Bahrain", code: "+973", iso: "BH", flag: "🇧🇭" },
  { country: "Bangladesh", code: "+880", iso: "BD", flag: "🇧🇩" },
  { country: "Belarus", code: "+375", iso: "BY", flag: "🇧🇾" },
  { country: "Belgium", code: "+32", iso: "BE", flag: "🇧🇪" },
  { country: "Belize", code: "+501", iso: "BZ", flag: "🇧🇿" },
  { country: "Benin", code: "+229", iso: "BJ", flag: "🇧🇯" },
  { country: "Bhutan", code: "+975", iso: "BT", flag: "🇧🇹" },
  { country: "Bolivia", code: "+591", iso: "BO", flag: "🇧🇴" },
  { country: "Bosnia and Herzegovina", code: "+387", iso: "BA", flag: "🇧🇦" },
  { country: "Botswana", code: "+267", iso: "BW", flag: "🇧🇼" },
  { country: "Brazil", code: "+55", iso: "BR", flag: "🇧🇷" },
  { country: "Brunei", code: "+673", iso: "BN", flag: "🇧🇳" },
  { country: "Bulgaria", code: "+359", iso: "BG", flag: "🇧🇬" },
  { country: "Burkina Faso", code: "+226", iso: "BF", flag: "🇧🇫" },
  { country: "Burundi", code: "+257", iso: "BI", flag: "🇧🇮" },
  { country: "Cambodia", code: "+855", iso: "KH", flag: "🇰🇭" },
  { country: "Cameroon", code: "+237", iso: "CM", flag: "🇨🇲" },
  { country: "Canada", code: "+1", iso: "CA", flag: "🇨🇦" },
  { country: "Central African Republic", code: "+236", iso: "CF", flag: "🇨🇫" },
  { country: "Chad", code: "+235", iso: "TD", flag: "🇹🇩" },
  { country: "Chile", code: "+56", iso: "CL", flag: "🇨🇱" },
  { country: "China", code: "+86", iso: "CN", flag: "🇨🇳" },
  { country: "Colombia", code: "+57", iso: "CO", flag: "🇨🇴" },
  { country: "Comoros", code: "+269", iso: "KM", flag: "🇰🇲" },
  { country: "Congo", code: "+242", iso: "CG", flag: "🇨🇬" },
  { country: "Costa Rica", code: "+506", iso: "CR", flag: "🇨🇷" },
  { country: "Croatia", code: "+385", iso: "HR", flag: "🇭🇷" },
  { country: "Cuba", code: "+53", iso: "CU", flag: "🇨🇺" },
  { country: "Cyprus", code: "+357", iso: "CY", flag: "🇨🇾" },
  { country: "Czech Republic", code: "+420", iso: "CZ", flag: "🇨🇿" },
  { country: "Denmark", code: "+45", iso: "DK", flag: "🇩🇰" },
  { country: "Djibouti", code: "+253", iso: "DJ", flag: "🇩🇯" },
  { country: "Dominican Republic", code: "+1-809", iso: "DO", flag: "🇩🇴" },
  { country: "Ecuador", code: "+593", iso: "EC", flag: "🇪🇨" },
  { country: "Egypt", code: "+20", iso: "EG", flag: "🇪🇬" },
  { country: "Eritrea", code: "+291", iso: "ER", flag: "🇪🇷" },
  { country: "Estonia", code: "+372", iso: "EE", flag: "🇪🇪" },
  { country: "Ethiopia", code: "+251", iso: "ET", flag: "🇪🇹" },
  { country: "Finland", code: "+358", iso: "FI", flag: "🇫🇮" },
  { country: "France", code: "+33", iso: "FR", flag: "🇫🇷" },
  { country: "Gabon", code: "+241", iso: "GA", flag: "🇬🇦" },
  { country: "Gambia", code: "+220", iso: "GM", flag: "🇬🇲" },
  { country: "Georgia", code: "+995", iso: "GE", flag: "🇬🇪" },
  { country: "Germany", code: "+49", iso: "DE", flag: "🇩🇪" },
  { country: "Ghana", code: "+233", iso: "GH", flag: "🇬🇭" },
  { country: "Greece", code: "+30", iso: "GR", flag: "🇬🇷" },
  { country: "Guatemala", code: "+502", iso: "GT", flag: "🇬🇹" },
  { country: "Guinea", code: "+224", iso: "GN", flag: "🇬🇳" },
  { country: "Guyana", code: "+592", iso: "GY", flag: "🇬🇾" },
  { country: "Haiti", code: "+509", iso: "HT", flag: "🇭🇹" },
  { country: "Honduras", code: "+504", iso: "HN", flag: "🇭🇳" },
  { country: "Hungary", code: "+36", iso: "HU", flag: "🇭🇺" },
  { country: "Iceland", code: "+354", iso: "IS", flag: "🇮🇸" },
  { country: "India", code: "+91", iso: "IN", flag: "🇮🇳" },
  { country: "Indonesia", code: "+62", iso: "ID", flag: "🇮🇩" },
  { country: "Iran", code: "+98", iso: "IR", flag: "🇮🇷" },
  { country: "Iraq", code: "+964", iso: "IQ", flag: "🇮🇶" },
  { country: "Ireland", code: "+353", iso: "IE", flag: "🇮🇪" },
  { country: "Israel", code: "+972", iso: "IL", flag: "🇮🇱" },
  { country: "Italy", code: "+39", iso: "IT", flag: "🇮🇹" },
  { country: "Ivory Coast", code: "+225", iso: "CI", flag: "🇨🇮" },
  { country: "Jamaica", code: "+1-876", iso: "JM", flag: "🇯🇲" },
  { country: "Japan", code: "+81", iso: "JP", flag: "🇯🇵" },
  { country: "Jordan", code: "+962", iso: "JO", flag: "🇯🇴" },
  { country: "Kazakhstan", code: "+7", iso: "KZ", flag: "🇰🇿" },
  { country: "Kenya", code: "+254", iso: "KE", flag: "🇰🇪" },
  { country: "Kuwait", code: "+965", iso: "KW", flag: "🇰🇼" },
  { country: "Kyrgyzstan", code: "+996", iso: "KG", flag: "🇰🇬" },
  { country: "Laos", code: "+856", iso: "LA", flag: "🇱🇦" },
  { country: "Latvia", code: "+371", iso: "LV", flag: "🇱🇻" },
  { country: "Lebanon", code: "+961", iso: "LB", flag: "🇱🇧" },
  { country: "Lesotho", code: "+266", iso: "LS", flag: "🇱🇸" },
  { country: "Liberia", code: "+231", iso: "LR", flag: "🇱🇷" },
  { country: "Libya", code: "+218", iso: "LY", flag: "🇱🇾" },
  { country: "Lithuania", code: "+370", iso: "LT", flag: "🇱🇹" },
  { country: "Luxembourg", code: "+352", iso: "LU", flag: "🇱🇺" },
  { country: "Madagascar", code: "+261", iso: "MG", flag: "🇲🇬" },
  { country: "Malawi", code: "+265", iso: "MW", flag: "🇲🇼" },
  { country: "Malaysia", code: "+60", iso: "MY", flag: "🇲🇾" },
  { country: "Maldives", code: "+960", iso: "MV", flag: "🇲🇻" },
  { country: "Mali", code: "+223", iso: "ML", flag: "🇲🇱" },
  { country: "Malta", code: "+356", iso: "MT", flag: "🇲🇹" },
  { country: "Mauritania", code: "+222", iso: "MR", flag: "🇲🇷" },
  { country: "Mauritius", code: "+230", iso: "MU", flag: "🇲🇺" },
  { country: "Mexico", code: "+52", iso: "MX", flag: "🇲🇽" },
  { country: "Moldova", code: "+373", iso: "MD", flag: "🇲🇩" },
  { country: "Monaco", code: "+377", iso: "MC", flag: "🇲🇨" },
  { country: "Mongolia", code: "+976", iso: "MN", flag: "🇲🇳" },
  { country: "Montenegro", code: "+382", iso: "ME", flag: "🇲🇪" },
  { country: "Morocco", code: "+212", iso: "MA", flag: "🇲🇦" },
  { country: "Mozambique", code: "+258", iso: "MZ", flag: "🇲🇿" },
  { country: "Myanmar", code: "+95", iso: "MM", flag: "🇲🇲" },
  { country: "Namibia", code: "+264", iso: "NA", flag: "🇳🇦" },
  { country: "Nepal", code: "+977", iso: "NP", flag: "🇳🇵" },
  { country: "Netherlands", code: "+31", iso: "NL", flag: "🇳🇱" },
  { country: "New Zealand", code: "+64", iso: "NZ", flag: "🇳🇿" },
  { country: "Nicaragua", code: "+505", iso: "NI", flag: "🇳🇮" },
  { country: "Niger", code: "+227", iso: "NE", flag: "🇳🇪" },
  { country: "Nigeria", code: "+234", iso: "NG", flag: "🇳🇬" },
  { country: "Norway", code: "+47", iso: "NO", flag: "🇳🇴" },
  { country: "Oman", code: "+968", iso: "OM", flag: "🇴🇲" },
  { country: "Pakistan", code: "+92", iso: "PK", flag: "🇵🇰" },
  { country: "Panama", code: "+507", iso: "PA", flag: "🇵🇦" },
  { country: "Papua New Guinea", code: "+675", iso: "PG", flag: "🇵🇬" },
  { country: "Paraguay", code: "+595", iso: "PY", flag: "🇵🇾" },
  { country: "Peru", code: "+51", iso: "PE", flag: "🇵🇪" },
  { country: "Philippines", code: "+63", iso: "PH", flag: "🇵🇭" },
  { country: "Poland", code: "+48", iso: "PL", flag: "🇵🇱" },
  { country: "Portugal", code: "+351", iso: "PT", flag: "🇵🇹" },
  { country: "Qatar", code: "+974", iso: "QA", flag: "🇶🇦" },
  { country: "Romania", code: "+40", iso: "RO", flag: "🇷🇴" },
  { country: "Russia", code: "+7", iso: "RU", flag: "🇷🇺" },
  { country: "Rwanda", code: "+250", iso: "RW", flag: "🇷🇼" },
  { country: "Saudi Arabia", code: "+966", iso: "SA", flag: "🇸🇦" },
  { country: "Senegal", code: "+221", iso: "SN", flag: "🇸🇳" },
  { country: "Serbia", code: "+381", iso: "RS", flag: "🇷🇸" },
  { country: "Sierra Leone", code: "+232", iso: "SL", flag: "🇸🇱" },
  { country: "Singapore", code: "+65", iso: "SG", flag: "🇸🇬" },
  { country: "Slovakia", code: "+421", iso: "SK", flag: "🇸🇰" },
  { country: "Slovenia", code: "+386", iso: "SI", flag: "🇸🇮" },
  { country: "Somalia", code: "+252", iso: "SO", flag: "🇸🇴" },
  { country: "South Africa", code: "+27", iso: "ZA", flag: "🇿🇦" },
  { country: "South Korea", code: "+82", iso: "KR", flag: "🇰🇷" },
  { country: "South Sudan", code: "+211", iso: "SS", flag: "🇸🇸" },
  { country: "Spain", code: "+34", iso: "ES", flag: "🇪🇸" },
  { country: "Sri Lanka", code: "+94", iso: "LK", flag: "🇱🇰" },
  { country: "Sudan", code: "+249", iso: "SD", flag: "🇸🇩" },
  { country: "Suriname", code: "+597", iso: "SR", flag: "🇸🇷" },
  { country: "Sweden", code: "+46", iso: "SE", flag: "🇸🇪" },
  { country: "Switzerland", code: "+41", iso: "CH", flag: "🇨🇭" },
  { country: "Syria", code: "+963", iso: "SY", flag: "🇸🇾" },
  { country: "Taiwan", code: "+886", iso: "TW", flag: "🇹🇼" },
  { country: "Tajikistan", code: "+992", iso: "TJ", flag: "🇹🇯" },
  { country: "Tanzania", code: "+255", iso: "TZ", flag: "🇹🇿" },
  { country: "Thailand", code: "+66", iso: "TH", flag: "🇹🇭" },
  { country: "Togo", code: "+228", iso: "TG", flag: "🇹🇬" },
  { country: "Trinidad and Tobago", code: "+1-868", iso: "TT", flag: "🇹🇹" },
  { country: "Tunisia", code: "+216", iso: "TN", flag: "🇹🇳" },
  { country: "Turkey", code: "+90", iso: "TR", flag: "🇹🇷" },
  { country: "Turkmenistan", code: "+993", iso: "TM", flag: "🇹🇲" },
  { country: "Uganda", code: "+256", iso: "UG", flag: "🇺🇬" },
  { country: "Ukraine", code: "+380", iso: "UA", flag: "🇺🇦" },
  { country: "United Arab Emirates", code: "+971", iso: "AE", flag: "🇦🇪" },
  { country: "United Kingdom", code: "+44", iso: "GB", flag: "🇬🇧" },
  { country: "United States", code: "+1", iso: "US", flag: "🇺🇸" },
  { country: "Uruguay", code: "+598", iso: "UY", flag: "🇺🇾" },
  { country: "Uzbekistan", code: "+998", iso: "UZ", flag: "🇺🇿" },
  { country: "Venezuela", code: "+58", iso: "VE", flag: "🇻🇪" },
  { country: "Vietnam", code: "+84", iso: "VN", flag: "🇻🇳" },
  { country: "Yemen", code: "+967", iso: "YE", flag: "🇾🇪" },
  { country: "Zambia", code: "+260", iso: "ZM", flag: "🇿🇲" },
  { country: "Zimbabwe", code: "+263", iso: "ZW", flag: "🇿🇼" },
];
